name: FireORM Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11' # Java 11+ is required for Firebase Emulator
          distribution: 'temurin'

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      - name: Install Dependencies
        run: go mod tidy

      - name: Start Firestore Emulator
        run: |
          nohup firebase emulators:start --only firestore > emulator.log 2>&1 &
          sleep 10 # Wait for the emulator to initialize

      - name: Run Tests
        env:
          FIRESTORE_EMULATOR_HOST: localhost:8080
        run: go test ./... -v

      - name: Stop Firestore Emulator
        run: |
          pkill -f "firebase emulators:start"
